# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: 50
  timeout: 5000
  extensions:
    - <%= SqliteVec.loadable_path %>

development:
  primary:
    <<: *default
    <% database_path = "storage/tenants/#{Rails.env}/%{tenant}/db/main.sqlite3" %>
    <% database_path = "file:#{database_path}?vfs=beamer" if %w[1 true].include?(ENV["BEAMER"]&.downcase) %>
    database: <%= database_path %>
    tenanted: true
  untenanted:
    <<: *default
    database: storage/untenanted/development.sqlite3
    migrations_paths: db/untenanted_migrate
  cable:
    <<: *default
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: storage/tenants/<%= Rails.env %>/%{tenant}/db/main.sqlite3
    tenanted: true
  untenanted:
    <<: *default
    database: storage/untenanted/test.sqlite3
    migrations_paths: db/untenanted_migrate

production: &production
  primary:
    <<: *default
    database: file:storage/tenants/<%= Rails.env %>/%{tenant}/db/main.sqlite3?vfs=beamer
    tenanted: true
    extensions:
      - <%= SqliteVec.loadable_path %>
  untenanted:
    <<: *default
    database: file:storage/untenanted/<%= Rails.env %>.sqlite3?vfs=beamer
    migrations_paths: db/untenanted_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate

beta: *production
staging: *production
