default: &default
  adapter: trilogy
  host: <%= ENV.fetch("MYSQL_HOST", "127.0.0.1") %>
  port: <%= ENV.fetch("MYSQL_PORT", "3306") %>
  username: <%= ENV.fetch("MYSQL_USER", "root") %>
  password: <%= ENV["MYSQL_PASSWORD"] %>
  encoding: utf8mb4
  pool: 50
  ssl_mode: <%= ENV["MYSQL_SSL_MODE"] %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: buzzy_development
  cable:
    <<: *default
    database: buzzy_development_cable
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: buzzy_test
  cable:
    <<: *default
    database: buzzy_test_cable
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: buzzy_production
  cable:
    <<: *default
    database: buzzy_production_cable
    migrations_paths: db/cable_migrate
  queue:
    <<: *default
    database: buzzy_production_queue
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: buzzy_production_cache
    migrations_paths: db/cache_migrate
